language: java
jdk:
  # junit5 requires java 8
  - oraclejdk8
  - oraclejdk9

addons:
    sonarcloud:
        organization: "robstoll-github"
        token:
            secure: $SONAR_TOKEN

before_install:
 - chmod +x gr
install: true

# -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/report.xml
# Unfortunately not yet ready, see:
# https://community.sonarsource.com/t/sonar-kotlin-coverage-fails-due-to-line-is-out-of-range-errors/3201/4

script:
  - ./gr -i build
  - |
      if [ $TRAVIS_JDK_VERSION == oraclejdk8 ]; then
          sonar-scanner \
              -Dsonar.projectKey=robstoll_niok \
              -Dsonar.sources=src \
              -Dsonar.projectVersion=0.3.0-SNAPSHOT
      fi

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
    - $HOME/.sonar/cache
