name: Windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 11, 14 ]

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: build without detekt
        run: ./gradlew build -x detekt
